language: java
notifications:
  email:
  - mds6@pdx.edu
  - rta@pdx.edu
  slack:
    secure: QSJUk2xIg3s3s8Zud0UGqpEMEveycNEUDH5MzRHLU96N8fwopD+KxajQcdDb3xhppXezMi9Y0yCfiuABHji43JHpwzcaXRfkQElF6j4mxhVHFIkfj0tqD55MRTsFoflA9+eEiFthqC1oDAR8jl/CWcPbWkunJp0hs5ya1OyfFl+66NUKefquNbmW5ckVUVRUex0Z1B1/hU0LFPcFkPGzOGRocvtfavcyrvB5cQ+boC8yVYyRJM1TxrVwpHdxOPAjM1LIGz/KSVzFXwtLbH9iFyUD/IO4lNDnwwCDBBuP44DkX3KRkgQxH26XjIWnl0ZfUp/7rggxgj6EQNx6AyQpjbFrzcedeiSOqptQjRyb/OdAHmRN6H31E85HxfiI6ha8ziu0/P0yoSQdnjDzTy/KNQl4JAlHq9mMyXfCWJrg5OzGUrYZQ4wCx53Jp7cDm4L96RF2OyL2eXE4GlzLR42ORApSSUsgn9akYg+rsnEsao4GuynGPEVUyp4wyQ2FsVM+GNIoozjTfGnqWQBvdBnXUbTtp8qMbK0TZIKR4OsxJ8im+jmSoRwj5HoNagBj4fNMm9I/USiBdk4t8AlfY1J2qyUVU+Kjw39Gz7PbXVoPhAzwQ3KIuSzOcfJ5PD3+8E5VcuOOuswGG5xV3ZwS/WHfUAF3649Ft8/csHt1U+VHy14=
